spring.application.name=com-hotels-hotel
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/?user=cpena
#spring.datasource.url=jdbc:mysql://localhost:3306/db_hotelsbook?useLegacyDatetimeCode=false&useSSL=false
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/db_hotelsbook?useLegacyDatetimeCode=false&useSSL=false
spring.datasource.username=cpena
spring.datasource.password=albino1487
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8082

#------- Microservicios

# URL del microservicio de servicios
microservice.services.url=http://services:8080/api/hotels/services
#microservice.services.url=http://localhost:8080/api/hotels/services

# URL del microservicio de reviews
microservice.reviews.url=http://reviews:8081/api/hotels/reviews
#microservice.reviews.url=http://localhost:8081/api/hotels/reviews

# URL para las imagenes
server.url=http://localhost:8082


#Logger
logging.level.root=INFO
logging.level.com.hotelsbook.services=DEBUG
logging.file.name=hotelsHotel
